-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bibtex",
      "c",
      "cpp",
      "cpp",
      "css",
      "csv",
      "dart",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "haskell",
      "html",
      "http",
      "javascript",
      "jinja",
      "jinja_inline",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "julia",
      "lua",
      "make",
      "markdown",
      "nginx",
      "notes",
      "python",
      "scss",
      "sql",
      "ssh_config",
      "styled",
      "svelte",
      "toml",
      "tsv",
      "tsx",
      "typescript",
      "typst",
      "vim",
      "vimdoc",
      "vue",
      "yaml",
    },
  },
}
